- name: Varible using in playbook
  hosts: localhost
  vars:
    name: durga
    role: system engineer
  tasks: trying to use varible's
  - name: using name varible
    ansible.builtin.debug:
     msg: "Hi this is {{name}}"

  - name: using role varible
    ansible.builtin.debug:
     msg: "Hi this is {{name}} and role is {{role}}"